DROP TABLE IF EXISTS lock_info;
CREATE TABLE lock_info
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	key VARCHAR(30) NULL DEFAULT NULL COMMENT 'key',
	time INT(20) NULL DEFAULT NULL COMMENT '锁定时间',
	time_unit VARCHAR(50) NULL DEFAULT NULL COMMENT '锁定时间单位',
	expire INT(20) NULL DEFAULT NULL COMMENT '过期时间'
	PRIMARY KEY (id)
);
